### ISSUE TITLE
Handle errors.

### ISSUE THREAD

**Issue by uxFeranmi** [team-wildcards/trip.com#10]
Handle errors and failed login on the login page. Need to wait for @iyke4life , @alfredpison & @cirqlar . Move associated project card to in-progress column when you get started.

**Comment by JonathanJude** [comment]
According to #14 
Frontend just needs to include this file:

`include('includes/config.php');`

on the `index.php` or any page

and use this code to display errors from backend
`<?php echo showAlert(); ?>`

Styling can be done around the code, like an alert card etc,

**Comment by cirqlar** [comment]
@JonathanJude could you expose some kind of variable so that the alert card can be wrapped in a conditional? (An if so the html isn't outputted when there's no alert)

**Comment by JonathanJude** [comment]
That makes sense.

@cirqlar Normally, I'd add the html for the alert card inside the function. But if not, what method or syntax would you suggest?

**Comment by cirqlar** [comment]
@JonathanJude I think we should just have the show alerts function return an object. Then we have `$alerts = showAlert();` and after that we can then do

`if ($alerts->any)` any would be a Boolean variable on the object that would be true when there's any alerts

Then, we could have `$alerts->message` as the variable that stores the alert message. Ideally, it should be an array of messages in case there's more than one.

**Comment by JonathanJude** [comment]
@cirqlar okay, would check that out.
