### ISSUE TITLE
Deploy to different environments with Environment Variables.

### ISSUE THREAD

**Issue by uxFeranmi** [team-wildcards/trip.com#11]
@team-wildcards/backend configure environment variables on Heroku to switch between database and filesystem implementation based on deployment environment.

**Comment by JonathanJude** [comment]
But, we aren't deploying our file system on heroku right?

**Comment by uxFeranmi** [comment]
No. That's for 000webhost

**Comment by JonathanJude** [comment]
WE don't need this anymore right?

**Comment by uxFeranmi** [comment]
I'm not sure. What's the status on the filesystem alternative?

**Comment by JonathanJude** [comment]
It's good.. But very hacky.. Can't be trusted.. I've ripped it off.. Since they're requesting we host it now, we're very safe.

Would close this now.
